### PR TITLE
Fix to use ModelLoader instead of DliLoader

### PR DESCRIPTION
**Pull request by bshsqa**

### CODE REVIEW

**Review by hinohie — APPROVED** [review]
Looks good to me but.. Is my approvement has any impact?

**Comment by adeelkazmi** [comment]
I've put this through the build server which is verifying it now

**Comment by adeelkazmi** [comment]
Ah, @hrdisaac says it will fail because it requires a toolkit patch too. Please reverify with that patch on the build server once it's approved :)

**Comment by hinohie** [comment]
This PR also need to dali-conformance-test PR be merged. That's why we cannot verify on dali server now :(

And also, 3D cache patch make a big big conflict. Please check our mail, and also please wait until @bshsqa resolve conflict.

**Comment by bshsqa** [comment]
Oh...
Now I am doing rebase my patch on top of Richard's Cache patch.

I will notice you when I finish to rebase the toolkit patch and than please merge this PR.
My tooklit patch needed to be merged with this visual test patch and conformance test patch and demo patch.

**Review by hrdisaac — APPROVED** [review]

**Pull request merged**
